Repository ucsc/ucsc-2022, pull requests merged in 2023-10, with the labels that each got.

#273 Pattern updates
  functions.php
  lib/blocks.php
  patterns/callout.php
  patterns/card-grid-2-columns.php
  patterns/card-grid-3-columns.php
  patterns/card-plain-cta.php
  patterns/card-plain.php
  patterns/card-yellow.php
  patterns/columns-1-call-to-action.php
  patterns/interstitial.php
  patterns/media-with-text-featured.php
  patterns/media-with-text-fixed-width.php
  patterns/page-header-breadcrumbs.php
  patterns/page-header-color-bar.php
Labels: change

#275 feat: ✨ Make Google site search the default
  src/scss/theme-regions/_site-content.scss
  templates/search.html
Labels: enhancement

#279 Tribe/sprint/imp
  parts/post-query.html
  parts/site-header.html
  patterns/card-grid-2-columns.php
  patterns/card-grid-3-columns.php
  patterns/card-plain-cta.php
  patterns/card-plain.php
  patterns/card-yellow.php
  patterns/grid-with-background-image.php
  patterns/map-contact.php
  patterns/media-with-text-featured.php
  patterns/post-query-card.php
  patterns/sidebar-with-navigation.php
  src/js/block-patterns/sidebar-with-navigation.js
  src/js/components/main-nav.js
  src/js/core/block-patterns.js
  src/js/core/ready.js
  src/scss/block-patterns/_cards.scss
  src/scss/block-patterns/_grid-with-background-image.scss
  src/scss/block-patterns/_map-contact.scss
  src/scss/block-patterns/_sidebar-with-navigation.scss
  src/scss/style.scss
  src/scss/theme-regions/_site-header.scss
  theme.json
Labels: sprint release

#274 fix: :bug: Correct issue of images breaking out of content area
  src/scss/base/_alignments.scss
  src/scss/style.scss
  wp-blocks/image.css
Labels: bug

#265 Herm71/issue252
  wp-blocks/accordion.css
Labels: change
